### ISSUE TITLE
Update Readme with project description

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/fedora-mailing-list-analysis#9]
As a contributor I would like to know the goals of this project so that my comments and contributions are helpful to the overall project. 

Acceptance Criteria: 

- [x] README includes project description and goals

**Comment by oindrillac** [comment]
@cdolfi here's the [template](https://github.com/aicoe-aiops/data-science-workflows/blob/master/docs/publish/project-document-template.md) that we have been using for our projects. as you already must be having most of the stuff outlined there already documented, you could reuse those to fill out sections from this document as you find relevant.

**Comment by cdolfi** [comment]
I will get on this asap
